"""llama.cpp / Ollama server launcher for GGUF models.

Serves GGUF-quantized models via llama.cpp's built-in server or
creates an Ollama Modelfile and registers the model for Ollama serving.

Usage::

    python deployment/serve_llamacpp.py --model checkpoints/gguf/model-q4_k_m.gguf \\
        --backend ollama --model-name minigpt
"""

from __future__ import annotations

import argparse
import logging
import os
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# llama.cpp server
# ---------------------------------------------------------------------------

def launch_llamacpp_server(
    model_path: str,
    host: str = "0.0.0.0",
    port: int = 8080,
    n_ctx: int = 4096,
    n_gpu_layers: int = -1,
    n_threads: int | None = None,
    n_batch: int = 512,
    llama_cpp_path: str | None = None,
) -> None:
    """Launch a llama.cpp HTTP server.

    Parameters
    ----------
    model_path:
        Path to the GGUF model file.
    host:
        Server host.
    port:
        Server port.
    n_ctx:
        Context window size.
    n_gpu_layers:
        Number of layers to offload to GPU. ``-1`` for all layers.
    n_threads:
        Number of CPU threads.
    n_batch:
        Batch size for prompt evaluation.
    llama_cpp_path:
        Path to llama.cpp build directory.
    """
    server_bin = _find_llama_server(llama_cpp_path)
    if not server_bin:
        logger.error(
            "llama.cpp server binary not found. Build llama.cpp:\n"
            "  git clone https://github.com/ggerganov/llama.cpp\n"
            "  cd llama.cpp && make llama-server"
        )
        raise FileNotFoundError("llama-server not found")

    cmd = [
        server_bin,
        "--model", model_path,
        "--host", host,
        "--port", str(port),
        "--ctx-size", str(n_ctx),
        "--n-gpu-layers", str(n_gpu_layers),
        "--batch-size", str(n_batch),
    ]

    if n_threads:
        cmd.extend(["--threads", str(n_threads)])

    logger.info("Launching llama.cpp server: %s", " ".join(cmd))
    logger.info("API at http://%s:%d", host, port)

    try:
        subprocess.run(cmd, check=True)
    except KeyboardInterrupt:
        logger.info("Server shut down by user")
    except subprocess.CalledProcessError as exc:
        logger.error("llama.cpp server exited with code %d", exc.returncode)
        raise


def _find_llama_server(llama_cpp_path: str | None = None) -> str | None:
    """Locate the llama.cpp server binary."""
    search_names = ["llama-server", "server"]

    if llama_cpp_path:
        base = Path(llama_cpp_path)
        for name in search_names:
            for sub in ["", "build/bin/", "build/"]:
                candidate = base / sub / name
                if candidate.exists():
                    return str(candidate)

    # Check PATH
    for name in search_names:
        found = shutil.which(name)
        if found:
            return found

    # Check common locations
    env_path = os.environ.get("LLAMA_CPP_PATH", "")
    if env_path:
        for name in search_names:
            candidate = Path(env_path) / name
            if candidate.exists():
                return str(candidate)

    return None


# ---------------------------------------------------------------------------
# Ollama integration
# ---------------------------------------------------------------------------

def create_ollama_modelfile(
    gguf_path: str,
    model_name: str = "minigpt",
    system_prompt: str = "You are a helpful assistant.",
    temperature: float = 0.7,
    context_length: int = 4096,
    output_path: str | None = None,
) -> str:
    """Generate an Ollama Modelfile for the GGUF model.

    Parameters
    ----------
    gguf_path:
        Absolute path to the GGUF model file.
    model_name:
        Name to register the model under in Ollama.
    system_prompt:
        Default system prompt.
    temperature:
        Default generation temperature.
    context_length:
        Default context window size.
    output_path:
        Path to write the Modelfile. Defaults to ``Modelfile`` in the
        GGUF directory.

    Returns
    -------
    str
        Path to the generated Modelfile.
    """
    gguf_abs = str(Path(gguf_path).resolve())

    modelfile_content = f"""# Ollama Modelfile for MiniGPT ({model_name})
# Auto-generated by MiniGPT deployment scripts

FROM {gguf_abs}

PARAMETER temperature {temperature}
PARAMETER num_ctx {context_length}
PARAMETER stop "<|endoftext|>"
PARAMETER stop "</s>"

SYSTEM \"\"\"{system_prompt}\"\"\"

TEMPLATE \"\"\"{{{{ if .System }}}}<|system|>
{{{{ .System }}}}<|end|>
{{{{ end }}}}{{{{ if .Prompt }}}}<|user|>
{{{{ .Prompt }}}}<|end|>
{{{{ end }}}}<|assistant|>
{{{{ .Response }}}}<|end|>\"\"\"
"""

    if output_path is None:
        output_path = str(Path(gguf_path).parent / "Modelfile")

    Path(output_path).write_text(modelfile_content)
    logger.info("Ollama Modelfile written to %s", output_path)
    return output_path


def register_ollama_model(
    modelfile_path: str,
    model_name: str = "minigpt",
) -> None:
    """Register a model with Ollama using the generated Modelfile.

    Parameters
    ----------
    modelfile_path:
        Path to the Ollama Modelfile.
    model_name:
        Name to register the model under.
    """
    cmd = ["ollama", "create", model_name, "-f", modelfile_path]
    logger.info("Registering model with Ollama: %s", " ".join(cmd))

    try:
        result = subprocess.run(cmd, check=True, capture_output=True, text=True)
        logger.info("Ollama model '%s' registered successfully", model_name)
        if result.stdout:
            logger.info("Ollama output: %s", result.stdout.strip())
    except FileNotFoundError:
        logger.error("Ollama not found. Install from https://ollama.com")
        raise
    except subprocess.CalledProcessError as exc:
        logger.error("Failed to register model: %s", exc.stderr)
        raise


def launch_ollama_serve(model_name: str = "minigpt") -> None:
    """Start serving a model via Ollama.

    Parameters
    ----------
    model_name:
        The registered model name to serve.
    """
    # Ensure Ollama is running
    try:
        subprocess.run(["ollama", "list"], check=True, capture_output=True)
    except (FileNotFoundError, subprocess.CalledProcessError):
        logger.info("Starting Ollama service...")
        subprocess.Popen(["ollama", "serve"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        import time
        time.sleep(2)

    logger.info("Starting Ollama model: %s", model_name)
    logger.info("API available at http://localhost:11434")

    cmd = ["ollama", "run", model_name]
    try:
        subprocess.run(cmd, check=True)
    except KeyboardInterrupt:
        logger.info("Ollama session ended by user")


def _load_cfg():
    """Load central config.yaml via OmegaConf (silent fallback if missing)."""
    try:
        from omegaconf import OmegaConf
        cfg_path = Path(__file__).resolve().parent.parent / "config.yaml"
        return OmegaConf.load(cfg_path)
    except Exception:
        return None


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")

    # Load central config — deployment parameters default from config.yaml
    cfg = _load_cfg()
    _d = cfg.deploy if cfg else None
    _p = cfg.paths  if cfg else None

    parser = argparse.ArgumentParser(description="llama.cpp / Ollama server launcher")
    parser.add_argument("--model",          default=None, help="Path to GGUF model file")
    parser.add_argument("--backend",        default=None, choices=["llamacpp", "ollama"])
    parser.add_argument("--model-name",     default=None, help="Model name for Ollama")
    parser.add_argument("--host",           default=None)
    parser.add_argument("--port",           type=int, default=None)
    parser.add_argument("--n-ctx",          type=int, default=None)
    parser.add_argument("--n-gpu-layers",   type=int, default=None)
    parser.add_argument("--llama-cpp-path", default=None)
    parser.add_argument("--system-prompt",  default=None)
    args = parser.parse_args()

    model_path  = args.model       or (str(_p.gguf_path)     if _p else None)
    backend     = args.backend     or "ollama"
    model_name  = args.model_name  or (str(_d.model_name)    if _d else "minigpt")
    host        = args.host        or (str(_d.host)           if _d else "0.0.0.0")
    port        = args.port        or (int(_d.port)           if _d else 8080)
    n_ctx       = args.n_ctx       or (int(_d.n_ctx)          if _d else 4096)
    n_gpu       = args.n_gpu_layers or (int(_d.n_gpu_layers)  if _d else -1)
    sys_prompt  = args.system_prompt or (str(_d.system_prompt) if _d else "You are a helpful assistant.")

    if not model_path:
        logger.error("No model path provided. Set paths.gguf_path in config.yaml or pass --model.")
        sys.exit(1)

    if backend == "llamacpp":
        launch_llamacpp_server(
            model_path=model_path,
            host=host,
            port=port,
            n_ctx=n_ctx,
            n_gpu_layers=n_gpu,
            llama_cpp_path=args.llama_cpp_path,
        )
    elif backend == "ollama":
        modelfile = create_ollama_modelfile(
            gguf_path=model_path,
            model_name=model_name,
            system_prompt=sys_prompt,
            context_length=n_ctx,
        )
        register_ollama_model(modelfile, model_name=model_name)
        launch_ollama_serve(model_name=model_name)


if __name__ == "__main__":
    main()
