"""Main pretraining entry point for MiniGPT.

Wraps TorchTitan for distributed pretraining with FSDP2, torch.compile,
bf16 mixed precision, gradient accumulation, and WandB logging.

Usage::

    # Train with a preset
    python training/train.py --preset tiny --dataset tinystories

    # Train with a custom TOML config (generated by toml_generator.py for TorchTitan)
    python training/train.py --toml /path/to/recipe.toml --use-torchtitan

    # Override specific parameters
    python training/train.py --preset small --lr 1e-4 --batch-size 16
"""

from __future__ import annotations

import argparse
import json
import logging
import math
import os
import sys
import time
import warnings
from pathlib import Path

import torch
import torch.nn as nn
from torch.optim import AdamW
from torch.optim.lr_scheduler import LambdaLR
from tqdm import tqdm

# Suppress noisy third-party warnings before any imports that trigger them
warnings.filterwarnings("ignore", message=".*complex operators.*", category=UserWarning)
warnings.filterwarnings("ignore", message=".*Torchinductor.*", category=UserWarning)
warnings.filterwarnings("ignore", message=".*resume_download.*", category=FutureWarning)
warnings.filterwarnings("ignore", message=".*use_auth_token.*", category=FutureWarning)
warnings.filterwarnings("ignore", category=FutureWarning, module="transformers")
warnings.filterwarnings("ignore", category=UserWarning, module="torch._inductor")

# Project imports
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from configs.model.config import ModelConfig, TrainingConfig, PRESETS
from miniGPT.model import MiniGPT
from training.data import build_pretraining_dataloader, load_tokenizer
from training.torchtitan_integration import (
    apply_activation_checkpointing,
    compile_model,
    get_autocast_context,
    register_minigpt,
)
from training.toml_generator import generate_toml

logger = logging.getLogger(__name__)


class _TqdmLoggingHandler(logging.StreamHandler):
    """Routes log records through tqdm.write() so bar lines are never corrupted."""

    def emit(self, record: logging.LogRecord) -> None:
        try:
            tqdm.write(self.format(record))
            self.flush()
        except Exception:
            self.handleError(record)


def _install_tqdm_logging(fmt: str) -> None:
    """Replace the root logger's StreamHandler with the tqdm-safe one."""
    root = logging.getLogger()
    for h in root.handlers[:]:
        if isinstance(h, logging.StreamHandler) and not isinstance(h, logging.FileHandler):
            root.removeHandler(h)
    handler = _TqdmLoggingHandler()
    handler.setFormatter(logging.Formatter(fmt))
    root.addHandler(handler)


# ---------------------------------------------------------------------------
# Learning rate schedule
# ---------------------------------------------------------------------------

def get_cosine_schedule_with_warmup(
    optimizer: torch.optim.Optimizer,
    warmup_steps: int,
    total_steps: int,
    min_lr_ratio: float = 0.1,
) -> LambdaLR:
    """Cosine learning rate schedule with linear warmup."""
    def lr_lambda(step: int) -> float:
        if step < warmup_steps:
            return step / max(1, warmup_steps)
        progress = (step - warmup_steps) / max(1, total_steps - warmup_steps)
        return min_lr_ratio + 0.5 * (1.0 - min_lr_ratio) * (1.0 + math.cos(math.pi * progress))

    return LambdaLR(optimizer, lr_lambda)


# ---------------------------------------------------------------------------
# TorchTitan launcher (if installed)
# ---------------------------------------------------------------------------

def run_with_torchtitan(toml_path: str) -> None:
    """Launch training via TorchTitan CLI with the given TOML config."""
    register_minigpt()
    try:
        import subprocess

        cmd = [
            sys.executable, "-m", "torchtitan.train",
            "--job.config_file", toml_path,
        ]
        logger.info("Launching TorchTitan: %s", " ".join(cmd))
        subprocess.run(cmd, check=True)
        return
    except (ImportError, FileNotFoundError):
        logger.warning("TorchTitan not available, falling back to built-in training loop")
    except subprocess.CalledProcessError as exc:
        logger.error("TorchTitan training failed with exit code %d", exc.returncode)
        raise


# ---------------------------------------------------------------------------
# Built-in training loop
# ---------------------------------------------------------------------------

def train(
    model_config: ModelConfig,
    training_config: TrainingConfig,
    *,
    dataset_name: str = "smollm",
    tokenizer_name: str = "meta-llama/Llama-3.2-1B",
    output_dir: str = "checkpoints",
    use_wandb: bool = True,
    resume_from: str | None = None,
) -> Path:
    """Run the pretraining loop."""
    device = "cuda" if torch.cuda.is_available() else "cpu"
    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    # ---- Model ----
    model = MiniGPT(model_config).to(device)
    param_info = model.count_parameters()
    logger.info("Model: %s  vocab=%d  seq_len=%d",
                param_info["total_human"], model_config.vocab_size, model_config.max_seq_len)

    if training_config.activation_checkpointing:
        try:
            apply_activation_checkpointing(model)
        except Exception as exc:
            logger.warning("Activation checkpointing unavailable: %s", exc)

    if training_config.compile and device == "cuda":
        try:
            model = compile_model(model)
        except Exception as exc:
            logger.warning("torch.compile unavailable: %s", exc)

    # ---- Optimizer ----
    optimizer = AdamW(
        model.parameters(),
        lr=training_config.lr,
        betas=(training_config.beta1, training_config.beta2),
        weight_decay=training_config.weight_decay,
        fused=device == "cuda",
    )

    total_steps = training_config.max_steps
    scheduler = get_cosine_schedule_with_warmup(
        optimizer,
        warmup_steps=training_config.warmup_steps,
        total_steps=total_steps,
    )

    # ---- Data ----
    grad_accum_steps = training_config.gradient_accumulation_steps
    effective_batch = training_config.batch_size * grad_accum_steps
    tokens_per_step = effective_batch * model_config.max_seq_len

    dataloader = build_pretraining_dataloader(
        dataset_name=dataset_name,
        tokenizer_name=tokenizer_name,
        max_seq_len=model_config.max_seq_len,
        batch_size=training_config.batch_size,
        max_tokens=None,
    )

    # ---- Resume ----
    start_step = 0
    if resume_from:
        ckpt = torch.load(resume_from, map_location=device, weights_only=False)
        model.load_state_dict(ckpt["model"])
        optimizer.load_state_dict(ckpt["optimizer"])
        scheduler.load_state_dict(ckpt["scheduler"])
        start_step = ckpt.get("step", 0)
        logger.info("Resumed from step %d", start_step)

    # ---- WandB ----
    if use_wandb:
        try:
            import wandb
            wandb.init(
                project="minigpt",
                config={
                    "model": model_config.__dict__,
                    "training": training_config.__dict__,
                    "dataset": dataset_name,
                },
            )
        except ImportError:
            logger.warning("wandb not installed, skipping logging")
            use_wandb = False

    # ---- Training loop ----
    model.train()
    step = start_step
    epoch = 0
    grad_norm = 0.0
    step_loss = float("nan")      # loss at the last completed step
    lr_current = training_config.lr
    tok_per_sec = 0.0             # smoothed throughput (updated at log_interval)

    # Interval tracking (for logger.info and tok/s)
    running_loss = 0.0
    interval_start = time.time()

    # Epoch-level loss (resets when a new epoch starts)
    epoch_loss_sum = 0.0
    epoch_steps = 0

    # Early stopping state
    patience = training_config.early_stopping_patience
    best_loss = float("inf")
    patience_counter = 0

    logger.info(
        "Training  steps=%d  batch=%d  grad_accum=%d  eff_batch=%d  tokens/step=%d  precision=bf16",
        total_steps, training_config.batch_size, grad_accum_steps, effective_batch, tokens_per_step,
    )

    pbar = tqdm(
        total=total_steps - start_step,
        initial=0,
        unit="step",
        desc="Training",
        dynamic_ncols=True,
        leave=True,
        bar_format=(
            "{desc}: {percentage:3.0f}%|{bar}| {n_fmt}/{total_fmt}"
            " [{elapsed}<{remaining}, {rate_fmt}{postfix}]"
        ),
    )

    def _refresh_bar() -> None:
        """Push current metrics into the tqdm postfix (called every log_interval steps)."""
        ep_avg = epoch_loss_sum / epoch_steps if epoch_steps else float("nan")
        d = pbar.format_dict
        rate = d.get("rate") or 0
        steps_left = (d.get("total") or total_steps) - (d.get("n") or step)
        if rate > 0 and steps_left > 0:
            secs = int(steps_left / rate)
            h, rem = divmod(secs, 3600)
            m, s = divmod(rem, 60)
            eta_str = f"{h:02d}h{m:02d}m{s:02d}s"
        else:
            eta_str = "N/A"
        pbar.set_postfix(ordered_dict={
            "ep":     epoch,
            "loss":   f"{step_loss:.4f}",
            "ep_avg": f"{ep_avg:.4f}",
            "lr":     f"{lr_current:.2e}",
            "gnorm":  f"{grad_norm:.2f}",
            "tok/s":  f"{tok_per_sec / 1000:.1f}K",
            "ETA":    eta_str,
        })

    data_iter = iter(dataloader)

    while step < total_steps:
        optimizer.zero_grad()
        accum_loss = 0.0

        for _ in range(grad_accum_steps):
            try:
                batch = next(data_iter)
            except StopIteration:
                # New epoch — reset epoch-level loss
                epoch += 1
                epoch_loss_sum = 0.0
                epoch_steps = 0
                data_iter = iter(dataloader)
                batch = next(data_iter)

            input_ids = batch["input_ids"].to(device)
            labels = batch["labels"].to(device)

            with get_autocast_context(device_type=device):
                outputs = model(input_ids, targets=labels)

            loss = outputs["loss"]
            aux_loss = outputs.get("aux_loss")
            if aux_loss is not None and aux_loss.item() > 0:
                loss = loss + aux_loss

            (loss / grad_accum_steps).backward()
            accum_loss += loss.item() / grad_accum_steps

        # Gradient clipping — capture norm before clipping
        if training_config.grad_clip > 0:
            grad_norm = torch.nn.utils.clip_grad_norm_(
                model.parameters(), training_config.grad_clip
            ).item()

        optimizer.step()
        scheduler.step()
        step += 1

        # Update per-step state
        step_loss = accum_loss
        lr_current = scheduler.get_last_lr()[0]
        running_loss += accum_loss
        epoch_loss_sum += accum_loss
        epoch_steps += 1

        pbar.update(1)

        # ---- Periodic logging + bar refresh ----
        if step % training_config.log_interval == 0:
            elapsed = time.time() - interval_start
            avg_loss = running_loss / training_config.log_interval
            tok_per_sec = training_config.log_interval * tokens_per_step / elapsed
            _refresh_bar()

            logger.info(
                "step=%d/%d  ep=%d  loss=%.4f  lr=%.2e  gnorm=%.2f  tok/s=%.0f",
                step, total_steps, epoch, avg_loss, lr_current, grad_norm, tok_per_sec,
            )

            if use_wandb:
                import wandb
                wandb.log({
                    "train/loss": avg_loss,
                    "train/lr": lr_current,
                    "train/grad_norm": grad_norm,
                    "train/tokens_per_sec": tok_per_sec,
                    "train/step": step,
                    "train/epoch": epoch,
                })
            running_loss = 0.0
            interval_start = time.time()

            # ---- Early stopping ----
            if patience > 0:
                if avg_loss < best_loss:
                    best_loss = avg_loss
                    patience_counter = 0
                else:
                    patience_counter += 1
                    logger.info(
                        "Loss did not improve (best=%.4f, patience %d/%d)",
                        best_loss, patience_counter, patience,
                    )
                    if patience_counter >= patience:
                        logger.info(
                            "Early stopping triggered at step %d — no improvement "
                            "for %d log-intervals (best=%.4f)",
                            step, patience, best_loss,
                        )
                        pbar.close()
                        break

        # ---- Checkpoint ----
        if step % training_config.save_interval == 0:
            ckpt_dir = out_path / f"step_{step}"
            ckpt_dir.mkdir(parents=True, exist_ok=True)
            torch.save(
                {
                    "model": model.state_dict(),
                    "optimizer": optimizer.state_dict(),
                    "scheduler": scheduler.state_dict(),
                    "step": step,
                    "epoch": epoch,
                    "model_config": model_config.__dict__,
                    "training_config": training_config.__dict__,
                },
                ckpt_dir / "checkpoint.pt",
            )
            with open(ckpt_dir / "config.json", "w") as f:
                json.dump(model_config.__dict__, f, indent=2, default=str)
            logger.info("Checkpoint saved → %s", ckpt_dir)

    pbar.close()

    # ---- Final save ----
    final_dir = out_path / "final"
    final_dir.mkdir(parents=True, exist_ok=True)
    torch.save(
        {
            "model": model.state_dict(),
            "step": step,
            "epoch": epoch,
            "model_config": model_config.__dict__,
            "training_config": training_config.__dict__,
        },
        final_dir / "checkpoint.pt",
    )
    with open(final_dir / "config.json", "w") as f:
        json.dump(model_config.__dict__, f, indent=2, default=str)

    if use_wandb:
        import wandb
        wandb.finish()

    logger.info("Training complete. Final checkpoint: %s", final_dir)
    return final_dir


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="MiniGPT Pretraining")

    parser.add_argument(
        "--preset", type=str, default=None,
        help=f"Model preset name. Options: {list(PRESETS.keys())}",
    )
    parser.add_argument(
        "--toml", type=str, default=None,
        help="Path to a TorchTitan TOML config file (overrides --preset).",
    )
    parser.add_argument("--dataset", type=str, default=None, help="Dataset name or HF path")
    parser.add_argument("--tokenizer", type=str, default=None)
    parser.add_argument("--output-dir", type=str, default=None)
    parser.add_argument("--lr", type=float, default=None)
    parser.add_argument("--batch-size", type=int, default=None)
    parser.add_argument("--max-steps", type=int, default=None)
    parser.add_argument("--warmup-steps", type=int, default=None)
    parser.add_argument("--grad-clip", type=float, default=None)
    parser.add_argument("--weight-decay", type=float, default=None)
    parser.add_argument("--gradient-accumulation-steps", type=int, default=None)
    parser.add_argument("--max-seq-len", type=int, default=None)
    parser.add_argument("--no-wandb", action="store_true")
    parser.add_argument("--no-compile", action="store_true")
    parser.add_argument("--resume", type=str, default=None, help="Checkpoint path to resume from")
    parser.add_argument("--use-torchtitan", action="store_true", help="Use TorchTitan launcher")

    return parser.parse_args()


DEFAULT_TOKENIZER = "HuggingFaceTB/cosmo2-tokenizer"


def _load_cfg():
    """Load central config.yaml via OmegaConf (silent fallback if missing)."""
    try:
        from omegaconf import OmegaConf
        cfg_path = Path(__file__).resolve().parent.parent / "config.yaml"
        return OmegaConf.load(cfg_path)
    except Exception:
        return None


def main() -> None:
    _LOG_FMT = "%(asctime)s %(levelname)s %(name)s: %(message)s"
    logging.basicConfig(level=logging.INFO, format=_LOG_FMT)
    _install_tqdm_logging(_LOG_FMT)

    cfg = _load_cfg()
    _t = cfg.training if cfg else None
    _m = cfg.model    if cfg else None
    _p = cfg.paths    if cfg else None

    args = parse_args()

    # If a TOML file is provided, try to launch via TorchTitan directly
    if args.toml:
        if args.use_torchtitan or (_t and _t.use_torchtitan):
            run_with_torchtitan(args.toml)
            return
        logger.info("TOML provided but use_torchtitan not set; using built-in loop")

    # Resolve model config — preset wins over individual fields
    preset = args.preset or (str(_m.preset) if _m and _m.preset else "tiny")
    if preset not in PRESETS:
        logger.error("Unknown preset '%s'. Available: %s", preset, list(PRESETS.keys()))
        sys.exit(1)
    model_config = PRESETS[preset]

    if _m and _m.vocab_size:
        model_config.vocab_size = int(_m.vocab_size)

    seq_len = args.max_seq_len or (int(_m.max_seq_len) if _m else None)
    if seq_len:
        model_config.max_seq_len = seq_len

    # Resolve training config — config.yaml values, CLI overrides on top
    training_config = TrainingConfig()
    if _t:
        training_config.lr                          = float(_t.lr)
        training_config.min_lr                      = float(_t.min_lr)
        training_config.beta1                       = float(_t.beta1)
        training_config.beta2                       = float(_t.beta2)
        training_config.weight_decay                = float(_t.weight_decay)
        training_config.grad_clip                   = float(_t.grad_clip)
        training_config.warmup_steps                = int(_t.warmup_steps)
        training_config.max_steps                   = int(_t.max_steps)
        training_config.batch_size                  = int(_t.batch_size)
        training_config.gradient_accumulation_steps = int(_t.gradient_accumulation_steps)
        training_config.activation_checkpointing    = bool(_t.activation_checkpointing)
        training_config.compile                     = bool(_t.compile)
        training_config.log_interval                = int(_t.log_interval)
        training_config.save_interval               = int(_t.save_interval)
        if hasattr(_t, "early_stopping_patience"):
            training_config.early_stopping_patience = int(_t.early_stopping_patience)

    # CLI overrides
    if args.lr is not None:                          training_config.lr = args.lr
    if args.batch_size is not None:                  training_config.batch_size = args.batch_size
    if args.max_steps is not None:                   training_config.max_steps = args.max_steps
    if args.warmup_steps is not None:                training_config.warmup_steps = args.warmup_steps
    if args.grad_clip is not None:                   training_config.grad_clip = args.grad_clip
    if args.weight_decay is not None:                training_config.weight_decay = args.weight_decay
    if args.gradient_accumulation_steps is not None:
        training_config.gradient_accumulation_steps = args.gradient_accumulation_steps
    if args.no_compile:                              training_config.compile = False

    # Resolve runtime arguments
    dataset    = args.dataset   or (str(_t.dataset)           if _t else "tinystories")
    tokenizer  = args.tokenizer or (str(cfg.data.tokenizer)   if cfg else DEFAULT_TOKENIZER)
    output_dir = args.output_dir or (
        str(Path(_p.checkpoints_dir) / "pretrain" / preset) if _p else "checkpoints"
    )
    use_wandb  = not args.no_wandb and (bool(_t.use_wandb) if _t else False)
    resume     = args.resume or (str(_t.resume_from) if _t and _t.resume_from else None)
    use_titan  = args.use_torchtitan or (bool(_t.use_torchtitan) if _t else False)

    # Generate TOML for TorchTitan if requested
    if use_titan and not args.toml:
        toml_path = Path(output_dir) / "generated_recipe.toml"
        toml_path.parent.mkdir(parents=True, exist_ok=True)
        generate_toml(model_config, training_config, output_path=str(toml_path))
        run_with_torchtitan(str(toml_path))
        return

    train(
        model_config=model_config,
        training_config=training_config,
        dataset_name=dataset,
        tokenizer_name=tokenizer,
        output_dir=output_dir,
        use_wandb=use_wandb,
        resume_from=resume,
    )


if __name__ == "__main__":
    main()
